### ISSUE TITLE
Micro Web Site

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-deeplink#1]
Hi, @Gianfranco97 

We need a Web Site to resolve deeplinks.

This is the format of the URL:
`https://flyve.org/flyve-mdm-deeplink/<base64>`

The base64 string contain this information:
`http://api.domain.com/glpi/apirest.php;45erjbudklq5865sdkjhjks;lkhjfkgsdf546634s;company's helpdesk;+33123456789;https://support.company.com;support@company.com;`

Please, show the support information with their proper url format (mailto:, callto:, http:...):

- Company name
- Phone
- URL
- Email

The deeplink to exec have this format:
`flyve://register?data={{base64encode CSV}}`

Please, also generate a QR image with the deeplink.

You can copy this design and sources to start: https://t.me/username
Use vanilla JS.

When the deeplink works (agent installed) the visibility change.
If the visibility does not change in few seconds.
We can detect the OS and redirect to the proper store (iTunnes or Google Play).

Google Play
https://play.google.com/store/apps/details?id=org.flyve.mdm.agent

iTunnes (App Store)
https://itunes.apple.com/us/app/flyve-mdm-agent

Reference:
https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

**Comment by Gianfranco97** [comment]
![127 0 0 1-8887--data y29tcgfuesdzighlbhbkzxnr kzmzmtizndu2nzg5 ahr0chm6ly9zdxbwb3j0lmnvbxbhbnkuy29t c3vwcg9ydebjb21wyw55lmnvbq](https://user-images.githubusercontent.com/19965590/30500076-cf8042f6-9a2a-11e7-860d-28c61398ece3.png)

**Comment by Gianfranco97** [comment]
link with which I am doing tests:
http://flyve.org/flyve-mdm-deeplink/?data=Y29tcGFueSdzIGhlbHBkZXNr;KzMzMTIzNDU2Nzg5;aHR0cHM6Ly9zdXBwb3J0LmNvbXBhbnkuY29t;c3VwcG9ydEBjb21wYW55LmNvbQ==

**Comment by ajsb85** [comment]
@Gianfranco97 Looks good 👍

**Comment by Gianfranco97** [comment]
is it normal to look like this?:
https://play.google.com/store/apps/details?id=org.flyve.mdm.agent
![captura de pantalla 2017-09-15 a la s 5 49 42 p m](https://user-images.githubusercontent.com/19965590/30504699-4d55f758-9a3e-11e7-9f29-f8ab474beea1.png)


I already tried with a VPN from Spain and it looks the same

**Comment by ajsb85** [comment]
@Gianfranco97 Its in beta. I can see the apk to dowload. I will add your email also. And yes its ok. 👌
