### ISSUE TITLE
Deeplink With internet Explorer.

### ISSUE THREAD

**Issue by spinaldf** [flyve-mdm/flyve-mdm-deeplink#35]
I check DeepLink on Internet Explorer doesn't Work Show QR Code.

I check on another Browsers. Firefox, Chrome and Opera. On these Browsers working.

Version Internet Explorer.

![ie](https://user-images.githubusercontent.com/42477982/45301215-ddb67480-b4e6-11e8-978d-82e2d15d1bdf.png)

![image001](https://user-images.githubusercontent.com/42477982/45301657-c88e1580-b4e7-11e8-955c-162aa0511ddc.png)

**Comment by Gianfranco97** [comment]
@spinaldf Thank you for reaching out, we will be adding this functionality as soon as we can
